
<ActionBtn@MDButton>:
  text: "Button"
  style: "filled"
  # x: 30
  # center_y: self.text
  # right: root.width - 10

  MDButtonText:
    text: root.text
    bold: True


<MainScreenView>
  md_bg_color: 1, 1, 1, 1

  MDLabel:
    id: title
    text: "FORECASTING APP"
    adaptive_size: True
    pos_hint: {"top": 0.9, "center_x": .5}
    bold: True
    font_style: "Title"
    role: "medium"

  MDButton:
    style: "outlined"
    x: 30
    center_y: title.center_y
    right: root.width - 10

    MDButtonText:
      text: "Analyze"
      bold: True

  ChartGraph:
    size_hint: .9, .55
    pos_hint: {"center_y": .5, "center_x": .5}
    # opacity: 0

  MDBoxLayout:
    pos_hint: {"center_x": .5, "center_y": .1}
    adaptive_size: True
    spacing: dp(16)

    ActionBtn:
      text: "Back"

    ActionBtn:
      text: "Refresh"

    ActionBtn:
      text: "Next"
