#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import QMDRecycleBoxLayout View.CommonScreen.components.recycleboxlayout.QMDRecycleBoxLayout

<ChatText>
  md_bg_color: get_color_from_hex("#ffeeff")
  line_color: get_color_from_hex("#1e1e1e")
  line_width: 1
  border_width: dp(2)
  padding: dp(4)
  radius: dp(4)
  text:""
  adaptive_height: True

  MDLabel:
    id: label
    padding: dp(4)
    text: root.text
    markup: True
    adaptive_height: True


<ChatList>
  viewclass: "ChatText"


  QMDRecycleBoxLayout:
    orientation: 'vertical'
    adaptive_height: True
    spacing: dp(24)
    padding: dp(8)
    key_size: "item_size"


<ChatContainer@MDBoxLayout>
  chat_list: chat_list
  md_bg_color: get_color_from_hex("#ffffff")
  radius: dp(10)
  line_color: get_color_from_hex("#1e1e1e")
  ChatList:
    id: chat_list



<ChatPanel@MDBoxLayout>
  action: None
  input_field: input_field
  md_bg_color: get_color_from_hex("#ffffff")
  line_color: get_color_from_hex("#1e1e1e")
  radius: dp(8)
  padding: dp(4)
  spacing: dp(8)
  adaptive_height: True
  
  
  MDTextField:
    id: input_field
    mode: "outlined"
    theme_line_color: "Custom"
    line_color_focus: get_color_from_hex("#ffffff00")
    line_color_normal: get_color_from_hex("#ffffff00")
    theme_text_color: "Custom"
    text_color_normal: get_color_from_hex("#1e1e1ebb")
    text_color_focus: get_color_from_hex("#1e1e1e")
    # text: "Hello\n"*10
    text: "plot and make forecast for makoko from quater of 2021"
    height: dp(48)
    # There is issues with multiline rendering
    # multiline: True
    # adaptive_height: True
    # max_height: dp(75)


  MDIconButton:
    icon: "send"
    style: "filled"
    on_press: root.action(input_field, input_field.text) if root.action is not None else None
    pos_hint: {"center_y": .5}
    theme_bg_color: "Custom"
    md_bg_color: get_color_from_hex("#ffffff")
    theme_icon_color: "Custom"
    icon_color: get_color_from_hex("#1e1e1e")
    size: dp(48), dp(48)
    theme_font_size: "Custom"
    font_size: sp(32)

<ChatLayout>
  md_bg_color: get_color_from_hex("#aeaeae")
  orientation: "vertical"
  padding: dp(16)
  spacing: dp(16)
  input_field: panel.input_field
  chat_list: wrapper.chat_list

  ChatContainer:
    id: wrapper

  ChatPanel:
    id: panel
    action: root.action
    height: dp(40)
